---
# tasks file for Windows beats deployment

- name: Copy over zip installer
  win_copy:
    src: /tmp/{{ beats }}-{{ version }}-windows-x86_64.zip
    dest: "C:\Program Files"
    remote_src: False 
