---
# tasks file for Windows beats deployment

- name: Copy over zip installer
  win_copy:
    src: /tmp/{{ beats }}-{{ version }}-windows-x86_64.zip
    dest: C:\
    remote_src: False 

- name: Unzip windows installer to Program Files
  win_unzip:
    src: C:\{{ beats }}-{{ version }}-windows-x86_64.zip
    dest: C:\
    creates: C:\{{ beats }}
    delete_archive: yes

- name: Copy a folder recursively where the source is on the remote host
  win_copy:
    src: C:\{{ beats }}-{{ version }}-windows-x86_64\
    dest: C:\Program Files\{{ beats }}
    remote_src: True

- name: Copy over uninstall previous verison J2
  win_template:
    src: powershellbeatuninstall.j2
    dest: C:\powershellbeatuninstall-{{ beats }}.ps1

- name: Run the powershell command on windows box
  win_shell: C:\powershellbeatuninstall-{{ beats }}.ps1
  args:

- name: Stop the "{{ beats }}" service
  win_shell: Stop-Service {{ beats }}
  args:
    chdir: C:\Program Files\{{ beats }}

- name: Copy over template powershellbeatinstall.j2
  win_template:
    src: powershellbeatinstall.j2
    dest: C:\powershellbeatinstall-{{ beats }}.ps1

- name: Run the powershell command on windows box
  win_shell: C:\powershellbeatinstall-{{ beats }}.ps1

- name: copying over beat.yml template
  win_template:
    src: "{{ role }}-{{ beats }}.j2"
    dest: C:\Program Files\{{ beats }}\{{ beats }}.yml

- name: Start the "{{ beats }}" service
  win_shell: Start-Service {{ beats }}
  args:
    chdir: C:\Program Files\{{ beats }}
